title: Works
description: >- # this means to ignore newlines until "baseurl:"
  My Works
baseurl: "/works" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  YumaYX

theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - makefile
  - mkpost
  - .jekyll-cache/
#   - .sass-cache/
#   - gemfiles/
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
